### PR TITLE
Add s390x arch support

### PR DESCRIPTION
**Pull request by raulcabello**

### CODE REVIEW

**Comment by raulcabello** [comment]
will use k3s-root binaries once this https://github.com/k3s-io/k3s-root/pull/43 is merged

**Comment by dweomer** [comment]
@raulcabello While I appreciate that you have adopted a pattern that was necessary-ish for the base build image I do not think we need to have a separate Dockerfile here. They are identical, no?

**Comment by dweomer** [comment]
> @raulcabello While I appreciate that you have adopted a pattern that was necessary-ish for the base build image I do not think we need to have a separate Dockerfile here. They are identical, no?

Ah, the goboring assertion. Well, there is no reason why that cannot be a conditional check (maybe even in a separate layer).

**Comment by raulcabello** [comment]
@dweomer I was using a separate Dockerfile because when I created this PR k3s-root binaries were not available for s390x. So I was using the container binaries instead. Notice there is no binaries downloaded from k3s-root and I was doing this instead https://github.com/rancher/image-build-kube-proxy/pull/12/files#diff-775c1f41e5f5a33ea531dbd04fce5572bc0bf32bbd54a9874c1985df12479de9R43-R44.

But I will change this to use k3s-root binaries (Thank you for getting the binaries for s390x :smile:  )
Then I will add a conditional for goboring as we are doing for other PRs such as https://github.com/rancher/image-build-crictl/pull/5/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R26-R28

I see that you already merged the k3s-root PR. Could you please create a release, so I can use the binaries?
Thanks!

**Comment by dweomer** [comment]
> I see that you already merged the k3s-root PR. Could you please create a release, so I can use the binaries?
> Thanks!

pre-release at the moment: https://github.com/k3s-io/k3s-root/releases/tag/v0.10.0-rc.0

**Comment by raulcabello** [comment]
@dweomer ah great! I didn't see that. Should I use the pre-release? That would mean using and if condition since the url is different than the amd64 one.

**Comment by dweomer** [comment]
@raulcabello yeah, go ahead and use the pre-release for now

**Comment by raulcabello** [comment]
@dweomer  done in the last commit. Please review it. Thanks

**Comment by dweomer** [comment]
So, looks like this repo is no longer used. We now leverage the rancher/hardened-kubernetes image for kube-proxy

**Comment by raulcabello** [comment]
It's still being used here https://github.com/rancher/image-build-dns-nodecache/blob/main/Dockerfile#L4, but I guess we can also use rancher/hardened-kubernetes there?

**Comment by raulcabello** [comment]
I just updated the PR https://github.com/rancher/image-build-kubernetes/pull/17

**Comment by raulcabello** [comment]
@dweomer Should I change https://github.com/rancher/image-build-dns-nodecache/blob/main/Dockerfile#L4 to use rancher/hardened-kubernetes instead of kube-proxy?

**Pull request merged**
